
POST http://localhost:3005/user/signin
Content-Type: application/json

{
    "email": "luka77@gmail.com",
    "password": "123456"
}


###
POST http://localhost:3005/pet/1/adopt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibHVrYTc3IiwiaWF0IjoxNjc3NzczMzk1fQ.0bM44ilSKsFw3c4QqhNKANpRt5RDiRxSPqK1km7n6Jo

###
POST http://localhost:3005/user/signup
Content-Type: application/json

{
    "email": "luka77@gmail.com",
    "password": "123456",
    "passwordVerify": "123456",
    "firstName": "Luka",
    "lastName": "Doncic",
    "phone": "0547669355"
}