#! SIGN-IN
POST http://localhost:3005/user/signin
Content-Type: application/json

{
    "email": "luka7711@gmail.com",
    "password": "123456"
}


###
#! MARK AS RESERVED FOR ADOPTION
POST http://localhost:3005/pet/1/adopt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibHVrYTc3IiwiaWF0IjoxNjc3NzczMzk1fQ.0bM44ilSKsFw3c4QqhNKANpRt5RDiRxSPqK1km7n6Jo

###
#! SIGN-UP
POST http://localhost:3005/user/signup
Content-Type: application/json

{
    "email": "luka7711@gmail.com",
    "password": "123456",
    "passwordVerify": "123456",
    "firstName": "Luka1",
    "lastName": "Doncic2",
    "phone": "0547669355"
}
###
#! SIGN-UP2
POST http://localhost:3005/user/signup
Content-Type: application/json

{
    "email": "lb000@gmail.com",
    "password": "123456",
    "passwordVerify": "123456",
    "firstName": "LeBron",
    "phone": "0547669355"
}

###
#! GET USER BY ID 
GET http://localhost:3005/user/640346e2ec94da3d8c35691c

###
#! GET ALL USERS  
GET  http://localhost:3005/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA0ZmM3MTE1NzcxZjI0Y2M1Y2ViYjQiLCJlbWFpbCI6Imx1a2E3NzExQGdtYWlsLmNvbSIsImlhdCI6MTY3ODA0ODM3N30.bUXZxbWV4SThLTIP85JU81yJ9KsQCn1pou40fD3wMys


###
#! DELETE USER 
DELETE http://localhost:3005/user/6403b1cd380939122837157c

###
#! UPDATE USER 
PATCH  http://localhost:3005/user/640346e2ec94da3d8c35691c
Content-Type: application/json

{
    "firstName": "LeBron",
    "lastName": "James",
    "phone": "212312324"
}